runner: "BBDMRunner"
training:
  n_epochs: 400
  n_steps: 300000
  save_interval: 20
  sample_interval: 4000
  validation_interval: 20
  accumulate_grad_batches: 4

testing:
  clip_denoised: False
  sample_num: 5

data:
  dataset_name: 'DIODE'
  dataset_type: 'diode'
  dataset_config:
    dataset_path: ''
    image_size: 256
    channels: 3
    to_normal: True
    flip: False
  train:
    batch_size: 8
    shuffle: True
  val:
    batch_size: 4
    shuffle: True
  test:
    batch_size: 8
    # shuffle: False

model:
  model_name: "BDBM_diode_x256_sum" # part of result path
  model_type: "BDBM" # specify a module
  latent_before_quant_conv: False
  normalize_latent: False
  only_load_latent_mean_std: False
  p_threshold: 0.5
  # model_load_path:  ""
  # optim_sche_load_path:  ""


  EMA:
    use_ema: True
    ema_decay: 0.995
    update_ema_interval: 8 # step
    start_ema_step: 30000

  CondStageParams:
    n_stages: 2
    in_channels: 6
    out_channels: 3

  BB:
    optimizer:
      weight_decay: 0.000
      optimizer: 'Adam'
      lr: 1.e-4
      beta1: 0.9

    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7

    params:
      mt_type: 'linear' # options {'linear', 'sin'}
      objective: 'sum' # options {'noise', 'sum', 'both'}
      loss_type: 'l2' # options {'l1', 'l2', 'recon'}

      skip_sample: True
      sample_type: 'linear' # options {"linear", "sin"}
      sample_step: 200

      num_timesteps: 1000 # timesteps
      eta: 1.0 # eta
      max_var: 1.0 # maximum variance

      UNetParams:
        image_size: 256
        in_channels: 9
        model_channels: 256
        out_channels: 3
        num_res_blocks: 2
        attention_resolutions: !!python/tuple
          - 32
          - 16
          - 8
        channel_mult: !!python/tuple
          - 1
          - 4
          - 8
        conv_resample: True
        dims: 2
        num_heads: 8
        num_head_channels: 64
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: False
        context_dim:
        condition_key: "dual"