runner: "BBDMRunner"
training:
  n_epochs: 1000
  n_steps: 300000
  save_interval: 20
  sample_interval: 2000
  validation_interval: 20
  accumulate_grad_batches: 2

testing:
  clip_denoised: False
  sample_num: 1

data:
  dataset_name: 'Night2Day'
  dataset_type: 'custom_aligned'
  dataset_config:
    dataset_path: ''
    image_size: 256
    channels: 3
    to_normal: True
    flip: False
  train:
    batch_size: 128
    shuffle: True
  val:
    batch_size: 4
    shuffle: True
  test:
    batch_size: 128
    # shuffle: False

model:
  model_name: "LBDBM-f8_night2day_x256_small" # part of result path
  model_type: "LBDBM" # specify a module
  latent_before_quant_conv: False
  normalize_latent: False
  only_load_latent_mean_std: False
  p_threshold: 0.5
  # model_load_path:  ""
  # optim_sche_load_path:  ""


  EMA:
    use_ema: True
    ema_decay: 0.995
    update_ema_interval: 8 # step
    start_ema_step: 30000

  CondStageParams:
    n_stages: 2
    in_channels: 6
    out_channels: 3
  
  VQGAN:
    params:
      ckpt_path: 'PRETRAINED ENCODER PATH'
      embed_dim: 4
      n_embed: 16384
      ddconfig:
        double_z: false
        z_channels: 4
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: !!python/tuple
          - 1
          - 2
          - 2
          - 4
        num_res_blocks: 2
        attn_resolutions:
          - 32
        dropout: 0.0

      lossconfig:
        target: torch.nn.Identity

  BB:
    optimizer:
      weight_decay: 0.000
      optimizer: 'Adam'
      lr: 1.e-4
      beta1: 0.9

    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7

    params:
      mt_type: 'linear' # options {'linear', 'sin'}
      objective: 'noise' # options {'noise', 'sum', 'both'}
      loss_type: 'l2' # options {'l1', 'l2', 'recon'}

      skip_sample: True
      sample_type: 'linear' # options {"linear", "sin"}
      sample_step: 35

      num_timesteps: 1000 # timesteps
      eta: 1.0 # eta
      max_var: 1.0 # maximum variance

      UNetParams:
        image_size: 32
        in_channels: 12
        model_channels: 256
        out_channels: 4
        num_res_blocks: 2
        attention_resolutions: !!python/tuple
          - 32
          - 16
          - 8
        channel_mult: !!python/tuple
          - 1
          - 2
          - 3
          - 4
        conv_resample: True
        dims: 2
        num_heads: 4
        num_head_channels: 64
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: False
        context_dim:
        condition_key: "dual" #{'dual', 'vae'} 'vae' will use VAE encoder of diffusers lib